# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 90e5a15f894a3a97c4160ca9a992525f76979a0a8fab4e1dfa8d0a1b0d9a73da478ae3e831a34cf415495ef912d0e3798f62339ec5bc2284837b703a53dfd04a

test:
  secret_key_base: 6dc4b6ff55a5359e619373f13bd815ba2a47568603a1f61100e3de81cfe460e21f50279f5030a31a69448f59f6ba81bbcd1e92db382ef0696e5dba4f8d9b5733

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
